"use client";

import { useState, useTransition } from "react";
import { recordAdjustment, recordMovement } from "../actions";
import { SelectField, TextField } from "@/components/form-fields";
import { Icon } from "@/components/icons";
import { useAlert } from "@/components/ui/alert-dialog";
import { Button } from "@/components/ui/button";
import { Card, CardHeader } from "@/components/ui/card";
import { PAYMENT_METHODS, type Bucket } from "@/types/investor";

type Kind = "deposit" | "withdrawal" | "adjustment";

const TITLES: Record<Kind, string> = {
    deposit: "Deposit",
    withdrawal: "Withdrawal",
    adjustment: "Adjustment",
};

function today(): string {
    return new Date().toISOString().slice(0, 10);
}

/**
 * FR-IVT-05, 06 and 08. The three lines a person may enter.
 *
 * Deployment, capital recovery, profit and loss lines are deliberately absent:
 * FR-IVT-07 makes them system-generated, so there is no form here that could
 * produce one — the same way the API has no route for it.
 */
export function MovementPanel({
    investorId,
    profitAvailable,
    principalAvailable,
}: {
    investorId: number;
    profitAvailable: string;
    principalAvailable: string;
}) {
    const { alert } = useAlert();
    const [kind, setKind] = useState<Kind | null>(null);
    const [amount, setAmount] = useState("");
    const [date, setDate] = useState(today());
    const [method, setMethod] = useState("Cash");
    const [bucket, setBucket] = useState<Bucket>("profit");
    const [reference, setReference] = useState("");
    const [reason, setReason] = useState("");
    const [pending, startTransition] = useTransition();

    function reset() {
        setKind(null);
        setAmount("");
        setReference("");
        setReason("");
        setDate(today());
    }

    function submit(event: React.FormEvent) {
        event.preventDefault();

        if (!kind) return;

        startTransition(async () => {
            const result =
                kind === "adjustment"
                    ? await recordAdjustment(investorId, {
                          amount: Number(amount),
                          bucket,
                          txn_date: date,
                          reason: reason.trim(),
                      })
                    : await recordMovement(
                          investorId,
                          kind === "deposit" ? "deposits" : "withdrawals",
                          {
                              amount: Number(amount),
                              txn_date: date,
                              method,
                              ...(kind === "withdrawal" ? { bucket } : {}),
                              reference: reference.trim() || undefined,
                          }
                      );

            if (result.ok) reset();

            void alert(
                result.ok
                    ? { title: result.message ?? "Recorded", tone: "success" }
                    : {
                          title: "That could not be recorded",
                          text: result.message ?? undefined,
                          tone: "error",
                      }
            );
        });
    }

    return (
        <Card>
            <CardHeader
                title="Record a movement"
                description="Deposits, withdrawals and corrections. Everything else on the ledger is generated by the system."
            />

            <div className="px-4 py-4 sm:px-5">
                {kind === null ? (
                    <div className="flex flex-wrap gap-2">
                        <Button size="sm" onClick={() => setKind("deposit")}>
                            <Icon name="plus" className="size-4" />
                            Deposit
                        </Button>
                        <Button
                            size="sm"
                            variant="secondary"
                            onClick={() => setKind("withdrawal")}
                        >
                            Withdrawal
                        </Button>
                        <Button
                            size="sm"
                            variant="secondary"
                            onClick={() => setKind("adjustment")}
                        >
                            Adjustment
                        </Button>
                    </div>
                ) : (
                    <form onSubmit={submit} className="flex flex-col gap-4">
                        <p className="text-sm font-medium text-foreground">
                            {TITLES[kind]}
                        </p>

                        {kind === "adjustment" ? (
                            <p className="rounded-md border border-border bg-surface-muted px-3 py-2 text-xs text-muted">
                                A correction, not an edit. Enter a{" "}
                                <span className="font-medium text-foreground">
                                    negative
                                </span>{" "}
                                amount to reduce the bucket and a positive one to
                                increase it. The original line stays where it is.
                            </p>
                        ) : null}

                        <div className="grid gap-4 sm:grid-cols-2">
                            <TextField
                                label="Amount (Rs.)"
                                name="amount"
                                type="number"
                                step="0.01"
                                required
                                // Only an adjustment may be negative.
                                min={kind === "adjustment" ? undefined : 0.01}
                                value={amount}
                                onChange={(event) =>
                                    setAmount(event.target.value)
                                }
                                hint={
                                    kind === "withdrawal"
                                        ? `Available: ${bucket === "profit" ? profitAvailable : principalAvailable}`
                                        : undefined
                                }
                            />
                            <TextField
                                label="Date"
                                name="txn_date"
                                type="date"
                                required
                                max={today()}
                                value={date}
                                onChange={(event) => setDate(event.target.value)}
                            />

                            {kind === "adjustment" ? null : (
                                <SelectField
                                    label="Method"
                                    name="method"
                                    options={PAYMENT_METHODS.map((entry) => ({
                                        value: entry,
                                        label: entry,
                                    }))}
                                    value={method}
                                    onChange={(event) =>
                                        setMethod(event.target.value)
                                    }
                                />
                            )}

                            {kind === "deposit" ? null : (
                                <SelectField
                                    label="Bucket"
                                    name="bucket"
                                    options={[
                                        { value: "profit", label: "Profit" },
                                        {
                                            value: "principal",
                                            label: "Principal",
                                        },
                                    ]}
                                    value={bucket}
                                    onChange={(event) =>
                                        setBucket(event.target.value as Bucket)
                                    }
                                    hint={
                                        kind === "withdrawal"
                                            ? "Profit first keeps original principal intact."
                                            : undefined
                                    }
                                />
                            )}

                            {kind === "adjustment" ? (
                                <div className="sm:col-span-2">
                                    <TextField
                                        label="Reason"
                                        name="reason"
                                        required
                                        maxLength={500}
                                        value={reason}
                                        onChange={(event) =>
                                            setReason(event.target.value)
                                        }
                                        placeholder="Deposit entered 100,000 too high"
                                    />
                                </div>
                            ) : (
                                <div className="sm:col-span-2">
                                    <TextField
                                        label="Reference"
                                        name="reference"
                                        maxLength={120}
                                        value={reference}
                                        onChange={(event) =>
                                            setReference(event.target.value)
                                        }
                                        placeholder="Cheque number, bank reference, or a short remark"
                                    />
                                </div>
                            )}
                        </div>

                        <div className="flex flex-col-reverse gap-2 sm:flex-row sm:justify-end">
                            <Button
                                type="button"
                                variant="secondary"
                                size="sm"
                                onClick={reset}
                            >
                                Cancel
                            </Button>
                            <Button
                                type="submit"
                                size="sm"
                                variant={
                                    kind === "deposit" ? "primary" : "secondary"
                                }
                                disabled={
                                    pending ||
                                    amount === "" ||
                                    (kind === "adjustment" &&
                                        reason.trim() === "")
                                }
                            >
                                {pending ? "Recording…" : `Record ${kind}`}
                            </Button>
                        </div>
                    </form>
                )}
            </div>
        </Card>
    );
}
