import {
  Column,
  CreateDateColumn,
  Entity,
  Index,
  JoinColumn,
  ManyToOne,
  PrimaryGeneratedColumn,
  type Relation,
} from 'typeorm';
import { Contract } from './contract.entity';
import { File } from './file.entity';
import { User } from './user.entity';

/** SRS §5.10 — immutable; replaces v1 recovery_reports. Module 7. */
@Entity('ledger_snapshots')
@Index('ledger_snapshots_contract_id_idx', ['contractId'])
export class LedgerSnapshot {
  @PrimaryGeneratedColumn('uuid')
  id: string;

  @Column({ name: 'contract_id', type: 'uuid' })
  contractId: string;

  @Index('ledger_snapshots_snapshot_no_key', { unique: true })
  @Column({ name: 'snapshot_no', type: 'varchar', length: 40 })
  snapshotNo: string;

  @Column({ type: 'jsonb' })
  payload: Record<string, unknown>;

  @Column({ name: 'pdf_file_id', type: 'text', nullable: true })
  pdfFileId: string | null;

  @Column({ name: 'created_by', type: 'uuid' })
  createdById: string;

  /** True for rows carried over from v1 rather than generated by v2. */
  @Column({ type: 'boolean', default: false })
  legacy: boolean;

  @CreateDateColumn({ name: 'created_at', type: 'timestamptz' })
  createdAt: Date;

  @ManyToOne(() => Contract, (contract) => contract.snapshots, {
    onDelete: 'RESTRICT',
  })
  @JoinColumn({ name: 'contract_id' })
  contract: Relation<Contract>;

  @ManyToOne(() => File, (file) => file.ledgerSnapshots, {
    nullable: true,
    onDelete: 'RESTRICT',
  })
  @JoinColumn({ name: 'pdf_file_id' })
  pdfFile: Relation<File> | null;

  @ManyToOne(() => User, (user) => user.ledgerSnapshots, {
    onDelete: 'RESTRICT',
  })
  @JoinColumn({ name: 'created_by' })
  createdBy: Relation<User>;
}
