import {
  Column,
  CreateDateColumn,
  Entity,
  Index,
  JoinColumn,
  ManyToOne,
  PrimaryGeneratedColumn,
  type Relation,
} from 'typeorm';
import { Contract } from './contract.entity';
import { File } from './file.entity';
import { User } from './user.entity';

/** SRS §5.10 — immutable; replaces v1 recovery_reports. Module 7. */
@Entity('ledger_snapshots')
@Index('ledger_snapshots_contract_id_idx', ['contract_id'])
export class LedgerSnapshot {
  @PrimaryGeneratedColumn()
  id: number;

  @Column({ type: 'integer' })
  contract_id: number;

  @Index('ledger_snapshots_snapshot_no_key', { unique: true })
  @Column({ type: 'varchar', length: 40 })
  snapshot_no: string;

  @Column({ type: 'jsonb' })
  payload: Record<string, unknown>;

  @Column({ type: 'integer', nullable: true })
  pdf_file_id: number | null;

  @Column({ type: 'integer' })
  created_by: number;

  /** True for rows carried over from v1 rather than generated by v2. */
  @Column({ type: 'boolean', default: false })
  legacy: boolean;

  @CreateDateColumn({ type: 'timestamptz' })
  created_at: Date;

  @ManyToOne(() => Contract, (contract) => contract.snapshots, {
    onDelete: 'RESTRICT',
  })
  @JoinColumn({ name: 'contract_id' })
  contract: Relation<Contract>;

  @ManyToOne(() => User, (user) => user.ledgerSnapshots, {
    onDelete: 'RESTRICT',
  })
  @JoinColumn({ name: 'created_by' })
  createdBy: Relation<User>;
}
